from tokenize import String
from pykson import JsonObject, ObjectListField, IntegerField, StringField, DateField, ObjectField, FloatField, JsonField
from ..address.addresses import OrderAddress, OrderShippingAddress
from ..contacts import OrderContact

class Customer(JsonObject):
    id = IntegerField()
    customerNo = StringField()
    name = StringField()
    userDef2 = StringField()
    invoiceType = StringField()
    foregroundColor = IntegerField()
    backgroundColor = IntegerField()


class Invoice(JsonObject):
    metadata = { 'endpoint': 'sales_history'}
    id = IntegerField()
    invoiceNo = StringField()
    invoiceDate = DateField()
    customer = ObjectField(Customer)
    orderNo = StringField()
    orderDate = DateField()
    total = FloatField(accepts_string=True)
    baseTotal = FloatField()
    grossProfit = FloatField()
    grossProfitMargin = FloatField()
    transNo = StringField()
    division = StringField()
    location = StringField()
    profitCenter = StringField()
    fob = StringField()
    incoterms = StringField()
    incotermsPlace = StringField()
    referenceNo = StringField()
    discount = FloatField(accepts_string=True)
    totalDiscount = FloatField(accepts_string=True)
    totalCostAverage = FloatField(accepts_string=True)
    totalCostCurrent = FloatField(accepts_string=True)
    totalCostStandard = FloatField(accepts_string=True)
    termsCode = StringField()
    termsText = StringField()
    customerPO = StringField()
    salespersonNo = StringField()
    salespersonName = StringField()
    subTotal = FloatField(accepts_string=True)
    territoryCode = StringField()
    freight = FloatField(accepts_string=True)
    weight = FloatField(accepts_string=True)
    shipDate = DateField()
    shippingCarrier = StringField()
    trackingNo = StringField()
    requiredDate = DateField()
    wasQuoteNo = StringField()
    jobNo = StringField()
    jobAccountNo = StringField()
    invoicedUser = StringField()
    currency = StringField()
    address = ObjectField(OrderAddress)
    shippingAddress = ObjectField(OrderShippingAddress)
    contact = ObjectField(OrderContact)
    createdBy = StringField()
    modifiedBy = StringField()
    created = StringField() 
    modified = StringField()
    links = JsonField()

class InvoiceList(JsonObject):
    records = ObjectListField(Invoice)
    start = IntegerField()
    limit = IntegerField()
    count = IntegerField()